### ISSUE TITLE
Discrepancy between saved subject 'verts' and those computed from parameters

### ISSUE THREAD

**Issue by purvaten** [otaheri/GOAL#4]
I found a discrepancy between (1) the subject vertices that are saved in the file `GNet_data.npy` under `'verts'` and (2) after computing them from the GT parameters provided in `GNet_data.npy`.

I am unsure if this is intentional or whether I am missing something. Here is the procedure I am following for re-computing the vertices (similar to what is done [here](https://github.com/otaheri/GOAL/blob/main/train/GNet_train.py#L560-L573)):

1. Use the keys `'fullpose_rotmat'` and `'transl'` from saved data and pass it to `parms_6D2full()` to compute full rotation matrix of subject.
2. Add the key `sbj_vtemp` from the saved data to the dict obtained in Step 1.
3. Depending on whether the GT gender is female or male, pass it through a model created with `SMPLXLayer` with `num_pca_comps=45`.
4. Obtain the vertices from Step 3.

I then reference the vertices in Step 4 at the saved indices `cfg.verts_sampled`, to get the vertices of size `(400, 3)`. I found that these do not exactly match those in the saved data for the key `'verts'` (they do not seem off by a large margin, but are not exactly the same either).

I believe this should be a problem as it appears that the saved `'verts'` are being used to compute the GT distance with the object (stored in `'verts2obj'`) against which the loss is computed [here](https://github.com/otaheri/GOAL/blob/main/train/GNet_train.py#L611-L613).

Please let me know if I am missing something. Thanks in advance!

**Comment by otaheri** [comment]
Hi @purvaten,

First of all, please make sure you are using the latest code on the repo. I updated some small bugs regarding how to pass the v-template to the model. I assume that is the issue here, in step 2. Instead of adding the sbj_vtemp as a key to the dict from step 1, please directly assign the vtemplate to the body model as in [here](https://github.com/otaheri/GOAL/blob/a287d9979c01a425ce83dafd396c88cc95b6bdc2/train/GNet_train.py#L397). Hopefully this will solve the issue. Please let me know if this works or not.
